//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public string Weight { get; set; }
        public string Origin { get; set; }
        public string GTN { get; set; }
        public string UID { get; set; }
        public string LOT { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string ImportedBy { get; set; }
        public string ImageUrl { get; set; }
        public string ScratchID { get; set; }
        public string GMP { get; set; }
    }
}
